"""update

Revision ID: 1750c252de01
Revises: 46605c8e9834
Create Date: 2022-05-08 14:10:19.859975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1750c252de01'
down_revision = '46605c8e9834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
