"""Create database

Revision ID: 1c44b197bd61
Revises: 4974d6d631a7
Create Date: 2022-04-29 23:02:42.336724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c44b197bd61'
down_revision = '4974d6d631a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
