"""update3

Revision ID: 4e68a1ed6ba8
Revises: ab23cf5927a6
Create Date: 2022-05-08 21:23:51.443684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e68a1ed6ba8'
down_revision = 'ab23cf5927a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
