"""add location

Revision ID: 78b30edced33
Revises: 75cea5d29b5b
Create Date: 2022-05-01 19:45:36.871061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b30edced33'
down_revision = '75cea5d29b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
