"""Create database

Revision ID: 7aac6216a42c
Revises: d0cea22e6893
Create Date: 2022-04-29 18:53:59.080978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aac6216a42c'
down_revision = 'd0cea22e6893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
