"""create

Revision ID: 9096ad5fa4b3
Revises: 0c4a609192ef
Create Date: 2022-05-01 10:27:16.954715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9096ad5fa4b3'
down_revision = '0c4a609192ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
