"""update2

Revision ID: ab23cf5927a6
Revises: 1750c252de01
Create Date: 2022-05-08 14:21:36.411143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab23cf5927a6'
down_revision = '1750c252de01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('last_modified_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'last_modified_date')
    # ### end Alembic commands ###
