"""Create database

Revision ID: b0f9ba96064e
Revises: 7aac6216a42c
Create Date: 2022-04-29 20:02:36.099605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f9ba96064e'
down_revision = '7aac6216a42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
