"""Create model

Revision ID: b334c3c3abaf
Revises: 52942f591e7e
Create Date: 2022-04-28 19:58:56.075707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b334c3c3abaf'
down_revision = '52942f591e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
